// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRfbd4eFL9NnlDHSkTeMupbmZOnu8QZu0',
    appId: '1:231480962803:web:b57d6b2dbd0de91dc9d186',
    messagingSenderId: '231480962803',
    projectId: 'lipreadapp',
    authDomain: 'lipreadapp.firebaseapp.com',
    storageBucket: 'lipreadapp.firebasestorage.app',
    measurementId: 'G-8CXYZRMYXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZK4rj5YgxRNmIvTZutRafB-TqtcbLcHg',
    appId: '1:231480962803:android:4d284d35b485e514c9d186',
    messagingSenderId: '231480962803',
    projectId: 'lipreadapp',
    storageBucket: 'lipreadapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUgzNrNL4Ql0SplYr9capBmonV8D1kHOU',
    appId: '1:231480962803:ios:328560afc92304a0c9d186',
    messagingSenderId: '231480962803',
    projectId: 'lipreadapp',
    storageBucket: 'lipreadapp.firebasestorage.app',
    androidClientId: '231480962803-f54p386s5ucn721i8lrug8kp9bib9uam.apps.googleusercontent.com',
    iosClientId: '231480962803-ossvfmad6lr2emu6vvsn3aiqbbou4pm0.apps.googleusercontent.com',
    iosBundleId: 'my.edu.tarumt.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUgzNrNL4Ql0SplYr9capBmonV8D1kHOU',
    appId: '1:231480962803:ios:328560afc92304a0c9d186',
    messagingSenderId: '231480962803',
    projectId: 'lipreadapp',
    storageBucket: 'lipreadapp.firebasestorage.app',
    androidClientId: '231480962803-f54p386s5ucn721i8lrug8kp9bib9uam.apps.googleusercontent.com',
    iosClientId: '231480962803-ossvfmad6lr2emu6vvsn3aiqbbou4pm0.apps.googleusercontent.com',
    iosBundleId: 'my.edu.tarumt.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRfbd4eFL9NnlDHSkTeMupbmZOnu8QZu0',
    appId: '1:231480962803:web:34b01fed4c64cbb5c9d186',
    messagingSenderId: '231480962803',
    projectId: 'lipreadapp',
    authDomain: 'lipreadapp.firebaseapp.com',
    storageBucket: 'lipreadapp.firebasestorage.app',
    measurementId: 'G-SVDE6VL0C9',
  );

}